name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      production:
        description: "Publish to production"
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run test
      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy${{ !inputs.production && ' --env preview' || '' }}
